//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace myData.Client.Schema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0", IsNullable=false)]
    public partial class ExpensesClassificationsDoc {
        
        private InvoiceExpensesClassificationType[] expensesInvoiceClassificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expensesInvoiceClassification")]
        public InvoiceExpensesClassificationType[] expensesInvoiceClassification {
            get {
                return this.expensesInvoiceClassificationField;
            }
            set {
                this.expensesInvoiceClassificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public partial class InvoiceExpensesClassificationType {
        
        private long invoiceMarkField;
        
        private long classificationMarkField;
        
        private bool classificationMarkFieldSpecified;
        
        private object[] itemsField;
        
        /// <remarks/>
        public long invoiceMark {
            get {
                return this.invoiceMarkField;
            }
            set {
                this.invoiceMarkField = value;
            }
        }
        
        /// <remarks/>
        public long classificationMark {
            get {
                return this.classificationMarkField;
            }
            set {
                this.classificationMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classificationMarkSpecified {
            get {
                return this.classificationMarkFieldSpecified;
            }
            set {
                this.classificationMarkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoicesExpensesClassificationDetails", typeof(InvoicesExpensesClassificationDetailType))]
        [System.Xml.Serialization.XmlElementAttribute("transactionMode", typeof(int))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public partial class InvoicesExpensesClassificationDetailType {
        
        private int lineNumberField;
        
        private ExpensesClassificationType[] expensesClassificationDetailDataField;
        
        /// <remarks/>
        public int lineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expensesClassificationDetailData")]
        public ExpensesClassificationType[] expensesClassificationDetailData {
            get {
                return this.expensesClassificationDetailDataField;
            }
            set {
                this.expensesClassificationDetailDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public partial class ExpensesClassificationType {
        
        private ExpensesClassificationTypeClassificationType classificationTypeField;
        
        private bool classificationTypeFieldSpecified;
        
        private ExpensesClassificationCategoryType classificationCategoryField;
        
        private bool classificationCategoryFieldSpecified;
        
        private decimal amountField;
        
        private sbyte idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        public ExpensesClassificationTypeClassificationType classificationType {
            get {
                return this.classificationTypeField;
            }
            set {
                this.classificationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classificationTypeSpecified {
            get {
                return this.classificationTypeFieldSpecified;
            }
            set {
                this.classificationTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ExpensesClassificationCategoryType classificationCategory {
            get {
                return this.classificationCategoryField;
            }
            set {
                this.classificationCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classificationCategorySpecified {
            get {
                return this.classificationCategoryFieldSpecified;
            }
            set {
                this.classificationCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public sbyte id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public enum ExpensesClassificationTypeClassificationType {
        
        /// <remarks/>
        E3_101,
        
        /// <remarks/>
        E3_102_001,
        
        /// <remarks/>
        E3_102_002,
        
        /// <remarks/>
        E3_102_003,
        
        /// <remarks/>
        E3_102_004,
        
        /// <remarks/>
        E3_102_005,
        
        /// <remarks/>
        E3_102_006,
        
        /// <remarks/>
        E3_104,
        
        /// <remarks/>
        E3_201,
        
        /// <remarks/>
        E3_202_001,
        
        /// <remarks/>
        E3_202_002,
        
        /// <remarks/>
        E3_202_003,
        
        /// <remarks/>
        E3_202_004,
        
        /// <remarks/>
        E3_202_005,
        
        /// <remarks/>
        E3_204,
        
        /// <remarks/>
        E3_207,
        
        /// <remarks/>
        E3_209,
        
        /// <remarks/>
        E3_301,
        
        /// <remarks/>
        E3_302_001,
        
        /// <remarks/>
        E3_302_002,
        
        /// <remarks/>
        E3_302_003,
        
        /// <remarks/>
        E3_302_004,
        
        /// <remarks/>
        E3_302_005,
        
        /// <remarks/>
        E3_304,
        
        /// <remarks/>
        E3_307,
        
        /// <remarks/>
        E3_309,
        
        /// <remarks/>
        E3_312,
        
        /// <remarks/>
        E3_313_001,
        
        /// <remarks/>
        E3_313_002,
        
        /// <remarks/>
        E3_313_003,
        
        /// <remarks/>
        E3_313_004,
        
        /// <remarks/>
        E3_313_005,
        
        /// <remarks/>
        E3_315,
        
        /// <remarks/>
        E3_581_001,
        
        /// <remarks/>
        E3_581_002,
        
        /// <remarks/>
        E3_581_003,
        
        /// <remarks/>
        E3_582,
        
        /// <remarks/>
        E3_583,
        
        /// <remarks/>
        E3_584,
        
        /// <remarks/>
        E3_585_001,
        
        /// <remarks/>
        E3_585_002,
        
        /// <remarks/>
        E3_585_003,
        
        /// <remarks/>
        E3_585_004,
        
        /// <remarks/>
        E3_585_005,
        
        /// <remarks/>
        E3_585_006,
        
        /// <remarks/>
        E3_585_007,
        
        /// <remarks/>
        E3_585_008,
        
        /// <remarks/>
        E3_585_009,
        
        /// <remarks/>
        E3_585_010,
        
        /// <remarks/>
        E3_585_011,
        
        /// <remarks/>
        E3_585_012,
        
        /// <remarks/>
        E3_585_013,
        
        /// <remarks/>
        E3_585_014,
        
        /// <remarks/>
        E3_585_015,
        
        /// <remarks/>
        E3_585_016,
        
        /// <remarks/>
        E3_586,
        
        /// <remarks/>
        E3_587,
        
        /// <remarks/>
        E3_588,
        
        /// <remarks/>
        E3_589,
        
        /// <remarks/>
        E3_881_001,
        
        /// <remarks/>
        E3_881_002,
        
        /// <remarks/>
        E3_881_003,
        
        /// <remarks/>
        E3_881_004,
        
        /// <remarks/>
        E3_882_001,
        
        /// <remarks/>
        E3_882_002,
        
        /// <remarks/>
        E3_882_003,
        
        /// <remarks/>
        E3_882_004,
        
        /// <remarks/>
        E3_883_001,
        
        /// <remarks/>
        E3_883_002,
        
        /// <remarks/>
        E3_883_003,
        
        /// <remarks/>
        E3_883_004,
        
        /// <remarks/>
        VAT_361,
        
        /// <remarks/>
        VAT_362,
        
        /// <remarks/>
        VAT_363,
        
        /// <remarks/>
        VAT_364,
        
        /// <remarks/>
        VAT_365,
        
        /// <remarks/>
        VAT_366,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public enum ExpensesClassificationCategoryType {
        
        /// <remarks/>
        category2_1,
        
        /// <remarks/>
        category2_2,
        
        /// <remarks/>
        category2_3,
        
        /// <remarks/>
        category2_4,
        
        /// <remarks/>
        category2_5,
        
        /// <remarks/>
        category2_6,
        
        /// <remarks/>
        category2_7,
        
        /// <remarks/>
        category2_8,
        
        /// <remarks/>
        category2_9,
        
        /// <remarks/>
        category2_10,
        
        /// <remarks/>
        category2_11,
        
        /// <remarks/>
        category2_12,
        
        /// <remarks/>
        category2_13,
        
        /// <remarks/>
        category2_14,
        
        /// <remarks/>
        category2_95,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0", IsNullable=false)]
    public partial class IncomeClassificationsDoc {
        
        private InvoiceIncomeClassificationType[] incomeInvoiceClassificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("incomeInvoiceClassification")]
        public InvoiceIncomeClassificationType[] incomeInvoiceClassification {
            get {
                return this.incomeInvoiceClassificationField;
            }
            set {
                this.incomeInvoiceClassificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public partial class InvoiceIncomeClassificationType {
        
        private long invoiceMarkField;
        
        private long classificationMarkField;
        
        private bool classificationMarkFieldSpecified;
        
        private object[] itemsField;
        
        /// <remarks/>
        public long invoiceMark {
            get {
                return this.invoiceMarkField;
            }
            set {
                this.invoiceMarkField = value;
            }
        }
        
        /// <remarks/>
        public long classificationMark {
            get {
                return this.classificationMarkField;
            }
            set {
                this.classificationMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classificationMarkSpecified {
            get {
                return this.classificationMarkFieldSpecified;
            }
            set {
                this.classificationMarkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoicesIncomeClassificationDetails", typeof(InvoicesIncomeClassificationDetailType))]
        [System.Xml.Serialization.XmlElementAttribute("transactionMode", typeof(int))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public partial class InvoicesIncomeClassificationDetailType {
        
        private int lineNumberField;
        
        private IncomeClassificationType[] incomeClassificationDetailDataField;
        
        /// <remarks/>
        public int lineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("incomeClassificationDetailData")]
        public IncomeClassificationType[] incomeClassificationDetailData {
            get {
                return this.incomeClassificationDetailDataField;
            }
            set {
                this.incomeClassificationDetailDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public partial class IncomeClassificationType {
        
        private IncomeClassificationValueType classificationTypeField;
        
        private IncomeClassificationCategoryType classificationCategoryField;
        
        private decimal amountField;
        
        private sbyte idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        public IncomeClassificationValueType classificationType {
            get {
                return this.classificationTypeField;
            }
            set {
                this.classificationTypeField = value;
            }
        }
        
        /// <remarks/>
        public IncomeClassificationCategoryType classificationCategory {
            get {
                return this.classificationCategoryField;
            }
            set {
                this.classificationCategoryField = value;
            }
        }
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public sbyte id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public enum IncomeClassificationValueType {
        
        /// <remarks/>
        E3_106,
        
        /// <remarks/>
        E3_205,
        
        /// <remarks/>
        E3_210,
        
        /// <remarks/>
        E3_305,
        
        /// <remarks/>
        E3_310,
        
        /// <remarks/>
        E3_318,
        
        /// <remarks/>
        E3_561_001,
        
        /// <remarks/>
        E3_561_002,
        
        /// <remarks/>
        E3_561_003,
        
        /// <remarks/>
        E3_561_004,
        
        /// <remarks/>
        E3_561_005,
        
        /// <remarks/>
        E3_561_006,
        
        /// <remarks/>
        E3_561_007,
        
        /// <remarks/>
        E3_562,
        
        /// <remarks/>
        E3_563,
        
        /// <remarks/>
        E3_564,
        
        /// <remarks/>
        E3_565,
        
        /// <remarks/>
        E3_566,
        
        /// <remarks/>
        E3_567,
        
        /// <remarks/>
        E3_568,
        
        /// <remarks/>
        E3_570,
        
        /// <remarks/>
        E3_595,
        
        /// <remarks/>
        E3_596,
        
        /// <remarks/>
        E3_597,
        
        /// <remarks/>
        E3_880_001,
        
        /// <remarks/>
        E3_880_002,
        
        /// <remarks/>
        E3_880_003,
        
        /// <remarks/>
        E3_880_004,
        
        /// <remarks/>
        E3_881_001,
        
        /// <remarks/>
        E3_881_002,
        
        /// <remarks/>
        E3_881_003,
        
        /// <remarks/>
        E3_881_004,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public enum IncomeClassificationCategoryType {
        
        /// <remarks/>
        category1_1,
        
        /// <remarks/>
        category1_2,
        
        /// <remarks/>
        category1_3,
        
        /// <remarks/>
        category1_4,
        
        /// <remarks/>
        category1_5,
        
        /// <remarks/>
        category1_6,
        
        /// <remarks/>
        category1_7,
        
        /// <remarks/>
        category1_8,
        
        /// <remarks/>
        category1_9,
        
        /// <remarks/>
        category1_10,
        
        /// <remarks/>
        category1_95,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0", IsNullable=false)]
    public partial class InvoicesDoc {
        
        private AadeBookInvoiceType[] invoiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoice")]
        public AadeBookInvoiceType[] invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class AadeBookInvoiceType {
        
        private string uidField;
        
        private long markField;
        
        private bool markFieldSpecified;
        
        private long cancelledByMarkField;
        
        private bool cancelledByMarkFieldSpecified;
        
        private string authenticationCodeField;
        
        private PartyType issuerField;
        
        private PartyType counterpartField;
        
        private InvoiceHeaderType invoiceHeaderField;
        
        private PaymentMethodDetailType[] paymentMethodsField;
        
        private InvoiceRowType[] invoiceDetailsField;
        
        private TaxTotalsType[] taxesTotalsField;
        
        private InvoiceSummaryType invoiceSummaryField;
        
        /// <remarks/>
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public long mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool markSpecified {
            get {
                return this.markFieldSpecified;
            }
            set {
                this.markFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long cancelledByMark {
            get {
                return this.cancelledByMarkField;
            }
            set {
                this.cancelledByMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cancelledByMarkSpecified {
            get {
                return this.cancelledByMarkFieldSpecified;
            }
            set {
                this.cancelledByMarkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string authenticationCode {
            get {
                return this.authenticationCodeField;
            }
            set {
                this.authenticationCodeField = value;
            }
        }
        
        /// <remarks/>
        public PartyType issuer {
            get {
                return this.issuerField;
            }
            set {
                this.issuerField = value;
            }
        }
        
        /// <remarks/>
        public PartyType counterpart {
            get {
                return this.counterpartField;
            }
            set {
                this.counterpartField = value;
            }
        }
        
        /// <remarks/>
        public InvoiceHeaderType invoiceHeader {
            get {
                return this.invoiceHeaderField;
            }
            set {
                this.invoiceHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("paymentMethodDetails", IsNullable=false)]
        public PaymentMethodDetailType[] paymentMethods {
            get {
                return this.paymentMethodsField;
            }
            set {
                this.paymentMethodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoiceDetails")]
        public InvoiceRowType[] invoiceDetails {
            get {
                return this.invoiceDetailsField;
            }
            set {
                this.invoiceDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("taxes", IsNullable=false)]
        public TaxTotalsType[] taxesTotals {
            get {
                return this.taxesTotalsField;
            }
            set {
                this.taxesTotalsField = value;
            }
        }
        
        /// <remarks/>
        public InvoiceSummaryType invoiceSummary {
            get {
                return this.invoiceSummaryField;
            }
            set {
                this.invoiceSummaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class PartyType {
        
        private string vatNumberField;
        
        private CountryType countryField;
        
        private int branchField;
        
        private string nameField;
        
        private AddressType addressField;
        
        /// <remarks/>
        public string vatNumber {
            get {
                return this.vatNumberField;
            }
            set {
                this.vatNumberField = value;
            }
        }
        
        /// <remarks/>
        public CountryType country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public int branch {
            get {
                return this.branchField;
            }
            set {
                this.branchField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public AddressType address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public enum CountryType {
        
        /// <remarks/>
        AD,
        
        /// <remarks/>
        AE,
        
        /// <remarks/>
        AF,
        
        /// <remarks/>
        AG,
        
        /// <remarks/>
        AI,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        AN,
        
        /// <remarks/>
        AO,
        
        /// <remarks/>
        AQ,
        
        /// <remarks/>
        AR,
        
        /// <remarks/>
        AS,
        
        /// <remarks/>
        AT,
        
        /// <remarks/>
        AU,
        
        /// <remarks/>
        AW,
        
        /// <remarks/>
        AX,
        
        /// <remarks/>
        AZ,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        BB,
        
        /// <remarks/>
        BD,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        BF,
        
        /// <remarks/>
        BG,
        
        /// <remarks/>
        BH,
        
        /// <remarks/>
        BI,
        
        /// <remarks/>
        BJ,
        
        /// <remarks/>
        BL,
        
        /// <remarks/>
        BM,
        
        /// <remarks/>
        BN,
        
        /// <remarks/>
        BO,
        
        /// <remarks/>
        BR,
        
        /// <remarks/>
        BS,
        
        /// <remarks/>
        BT,
        
        /// <remarks/>
        BV,
        
        /// <remarks/>
        BW,
        
        /// <remarks/>
        BY,
        
        /// <remarks/>
        BZ,
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        CC,
        
        /// <remarks/>
        CD,
        
        /// <remarks/>
        CF,
        
        /// <remarks/>
        CG,
        
        /// <remarks/>
        CH,
        
        /// <remarks/>
        CI,
        
        /// <remarks/>
        CK,
        
        /// <remarks/>
        CL,
        
        /// <remarks/>
        CM,
        
        /// <remarks/>
        CN,
        
        /// <remarks/>
        CO,
        
        /// <remarks/>
        CR,
        
        /// <remarks/>
        CU,
        
        /// <remarks/>
        CV,
        
        /// <remarks/>
        CX,
        
        /// <remarks/>
        CY,
        
        /// <remarks/>
        CZ,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        DJ,
        
        /// <remarks/>
        DK,
        
        /// <remarks/>
        DM,
        
        /// <remarks/>
        DO,
        
        /// <remarks/>
        DZ,
        
        /// <remarks/>
        EC,
        
        /// <remarks/>
        EE,
        
        /// <remarks/>
        EG,
        
        /// <remarks/>
        EH,
        
        /// <remarks/>
        ER,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        ET,
        
        /// <remarks/>
        FI,
        
        /// <remarks/>
        FJ,
        
        /// <remarks/>
        FK,
        
        /// <remarks/>
        FM,
        
        /// <remarks/>
        FO,
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        GA,
        
        /// <remarks/>
        GB,
        
        /// <remarks/>
        GD,
        
        /// <remarks/>
        GE,
        
        /// <remarks/>
        GF,
        
        /// <remarks/>
        GG,
        
        /// <remarks/>
        GH,
        
        /// <remarks/>
        GI,
        
        /// <remarks/>
        GL,
        
        /// <remarks/>
        GM,
        
        /// <remarks/>
        GN,
        
        /// <remarks/>
        GP,
        
        /// <remarks/>
        GQ,
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        GS,
        
        /// <remarks/>
        GT,
        
        /// <remarks/>
        GU,
        
        /// <remarks/>
        GW,
        
        /// <remarks/>
        GY,
        
        /// <remarks/>
        HK,
        
        /// <remarks/>
        HM,
        
        /// <remarks/>
        HN,
        
        /// <remarks/>
        HR,
        
        /// <remarks/>
        HT,
        
        /// <remarks/>
        HU,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        IE,
        
        /// <remarks/>
        IL,
        
        /// <remarks/>
        IM,
        
        /// <remarks/>
        IN,
        
        /// <remarks/>
        IO,
        
        /// <remarks/>
        IQ,
        
        /// <remarks/>
        IR,
        
        /// <remarks/>
        IS,
        
        /// <remarks/>
        IT,
        
        /// <remarks/>
        JE,
        
        /// <remarks/>
        JM,
        
        /// <remarks/>
        JO,
        
        /// <remarks/>
        JP,
        
        /// <remarks/>
        KE,
        
        /// <remarks/>
        KG,
        
        /// <remarks/>
        KH,
        
        /// <remarks/>
        KI,
        
        /// <remarks/>
        KM,
        
        /// <remarks/>
        KN,
        
        /// <remarks/>
        KP,
        
        /// <remarks/>
        KR,
        
        /// <remarks/>
        KW,
        
        /// <remarks/>
        KY,
        
        /// <remarks/>
        KZ,
        
        /// <remarks/>
        LA,
        
        /// <remarks/>
        LB,
        
        /// <remarks/>
        LC,
        
        /// <remarks/>
        LI,
        
        /// <remarks/>
        LK,
        
        /// <remarks/>
        LR,
        
        /// <remarks/>
        LS,
        
        /// <remarks/>
        LT,
        
        /// <remarks/>
        LU,
        
        /// <remarks/>
        LV,
        
        /// <remarks/>
        LY,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MC,
        
        /// <remarks/>
        MD,
        
        /// <remarks/>
        ME,
        
        /// <remarks/>
        MF,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        MH,
        
        /// <remarks/>
        MK,
        
        /// <remarks/>
        ML,
        
        /// <remarks/>
        MM,
        
        /// <remarks/>
        MN,
        
        /// <remarks/>
        MO,
        
        /// <remarks/>
        MP,
        
        /// <remarks/>
        MQ,
        
        /// <remarks/>
        MR,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        MU,
        
        /// <remarks/>
        MV,
        
        /// <remarks/>
        MW,
        
        /// <remarks/>
        MX,
        
        /// <remarks/>
        MY,
        
        /// <remarks/>
        MZ,
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        NC,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        NF,
        
        /// <remarks/>
        NG,
        
        /// <remarks/>
        NI,
        
        /// <remarks/>
        NL,
        
        /// <remarks/>
        NO,
        
        /// <remarks/>
        NP,
        
        /// <remarks/>
        NR,
        
        /// <remarks/>
        NU,
        
        /// <remarks/>
        NZ,
        
        /// <remarks/>
        OM,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PF,
        
        /// <remarks/>
        PG,
        
        /// <remarks/>
        PH,
        
        /// <remarks/>
        PK,
        
        /// <remarks/>
        PL,
        
        /// <remarks/>
        PM,
        
        /// <remarks/>
        PN,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        PT,
        
        /// <remarks/>
        PW,
        
        /// <remarks/>
        PY,
        
        /// <remarks/>
        QA,
        
        /// <remarks/>
        RE,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RS,
        
        /// <remarks/>
        RU,
        
        /// <remarks/>
        RW,
        
        /// <remarks/>
        SA,
        
        /// <remarks/>
        SB,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SD,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        SG,
        
        /// <remarks/>
        SH,
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        SJ,
        
        /// <remarks/>
        SK,
        
        /// <remarks/>
        SL,
        
        /// <remarks/>
        SM,
        
        /// <remarks/>
        SN,
        
        /// <remarks/>
        SO,
        
        /// <remarks/>
        SR,
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        SV,
        
        /// <remarks/>
        SY,
        
        /// <remarks/>
        SZ,
        
        /// <remarks/>
        TC,
        
        /// <remarks/>
        TD,
        
        /// <remarks/>
        TF,
        
        /// <remarks/>
        TG,
        
        /// <remarks/>
        TH,
        
        /// <remarks/>
        TJ,
        
        /// <remarks/>
        TK,
        
        /// <remarks/>
        TL,
        
        /// <remarks/>
        TM,
        
        /// <remarks/>
        TN,
        
        /// <remarks/>
        TO,
        
        /// <remarks/>
        TR,
        
        /// <remarks/>
        TT,
        
        /// <remarks/>
        TV,
        
        /// <remarks/>
        TW,
        
        /// <remarks/>
        TZ,
        
        /// <remarks/>
        UA,
        
        /// <remarks/>
        UG,
        
        /// <remarks/>
        UM,
        
        /// <remarks/>
        US,
        
        /// <remarks/>
        UY,
        
        /// <remarks/>
        UZ,
        
        /// <remarks/>
        VA,
        
        /// <remarks/>
        VC,
        
        /// <remarks/>
        VE,
        
        /// <remarks/>
        VG,
        
        /// <remarks/>
        VI,
        
        /// <remarks/>
        VN,
        
        /// <remarks/>
        VU,
        
        /// <remarks/>
        WF,
        
        /// <remarks/>
        WS,
        
        /// <remarks/>
        YE,
        
        /// <remarks/>
        YT,
        
        /// <remarks/>
        ZA,
        
        /// <remarks/>
        ZM,
        
        /// <remarks/>
        ZW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class AddressType {
        
        private string streetField;
        
        private string numberField;
        
        private string postalCodeField;
        
        private string cityField;
        
        /// <remarks/>
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class InvoiceHeaderType {
        
        private string seriesField;
        
        private string aaField;
        
        private System.DateTime issueDateField;
        
        private InvoiceType invoiceTypeField;
        
        private bool vatPaymentSuspensionField;
        
        private bool vatPaymentSuspensionFieldSpecified;
        
        private CurrencyType currencyField;
        
        private bool currencyFieldSpecified;
        
        private decimal exchangeRateField;
        
        private bool exchangeRateFieldSpecified;
        
        private long[] correlatedInvoicesField;
        
        private bool selfPricingField;
        
        private bool selfPricingFieldSpecified;
        
        private System.DateTime dispatchDateField;
        
        private bool dispatchDateFieldSpecified;
        
        private System.DateTime dispatchTimeField;
        
        private bool dispatchTimeFieldSpecified;
        
        private string vehicleNumberField;
        
        private int movePurposeField;
        
        private bool movePurposeFieldSpecified;
        
        /// <remarks/>
        public string series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        public string aa {
            get {
                return this.aaField;
            }
            set {
                this.aaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        public InvoiceType invoiceType {
            get {
                return this.invoiceTypeField;
            }
            set {
                this.invoiceTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool vatPaymentSuspension {
            get {
                return this.vatPaymentSuspensionField;
            }
            set {
                this.vatPaymentSuspensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vatPaymentSuspensionSpecified {
            get {
                return this.vatPaymentSuspensionFieldSpecified;
            }
            set {
                this.vatPaymentSuspensionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CurrencyType currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currencySpecified {
            get {
                return this.currencyFieldSpecified;
            }
            set {
                this.currencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal exchangeRate {
            get {
                return this.exchangeRateField;
            }
            set {
                this.exchangeRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool exchangeRateSpecified {
            get {
                return this.exchangeRateFieldSpecified;
            }
            set {
                this.exchangeRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("correlatedInvoices")]
        public long[] correlatedInvoices {
            get {
                return this.correlatedInvoicesField;
            }
            set {
                this.correlatedInvoicesField = value;
            }
        }
        
        /// <remarks/>
        public bool selfPricing {
            get {
                return this.selfPricingField;
            }
            set {
                this.selfPricingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool selfPricingSpecified {
            get {
                return this.selfPricingFieldSpecified;
            }
            set {
                this.selfPricingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dispatchDate {
            get {
                return this.dispatchDateField;
            }
            set {
                this.dispatchDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dispatchDateSpecified {
            get {
                return this.dispatchDateFieldSpecified;
            }
            set {
                this.dispatchDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime dispatchTime {
            get {
                return this.dispatchTimeField;
            }
            set {
                this.dispatchTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dispatchTimeSpecified {
            get {
                return this.dispatchTimeFieldSpecified;
            }
            set {
                this.dispatchTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string vehicleNumber {
            get {
                return this.vehicleNumberField;
            }
            set {
                this.vehicleNumberField = value;
            }
        }
        
        /// <remarks/>
        public int movePurpose {
            get {
                return this.movePurposeField;
            }
            set {
                this.movePurposeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool movePurposeSpecified {
            get {
                return this.movePurposeFieldSpecified;
            }
            set {
                this.movePurposeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public enum InvoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.1")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.2")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.3")]
        Item13,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.4")]
        Item14,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.5")]
        Item15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.6")]
        Item16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.1")]
        Item21,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.2")]
        Item22,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.3")]
        Item23,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.4")]
        Item24,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3.1")]
        Item31,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3.2")]
        Item32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5.1")]
        Item51,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5.2")]
        Item52,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6.1")]
        Item61,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6.2")]
        Item62,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7.1")]
        Item71,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8.1")]
        Item81,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8.2")]
        Item82,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11.1")]
        Item111,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11.2")]
        Item112,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11.3")]
        Item113,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11.4")]
        Item114,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11.5")]
        Item115,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item121,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13.1")]
        Item131,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13.2")]
        Item132,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13.3")]
        Item133,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13.4")]
        Item134,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13.30")]
        Item1330,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13.31")]
        Item1331,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14.1")]
        Item141,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14.2")]
        Item142,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14.3")]
        Item143,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14.4")]
        Item144,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14.5")]
        Item145,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14.30")]
        Item1430,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14.31")]
        Item1431,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15.1")]
        Item151,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16.1")]
        Item161,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17.1")]
        Item171,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17.2")]
        Item172,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17.3")]
        Item173,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17.4")]
        Item174,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17.5")]
        Item175,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17.6")]
        Item176,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public enum CurrencyType {
        
        /// <remarks/>
        AED,
        
        /// <remarks/>
        AFN,
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        AMD,
        
        /// <remarks/>
        ANG,
        
        /// <remarks/>
        AOA,
        
        /// <remarks/>
        ARS,
        
        /// <remarks/>
        AUD,
        
        /// <remarks/>
        AWG,
        
        /// <remarks/>
        AZN,
        
        /// <remarks/>
        BAM,
        
        /// <remarks/>
        BBD,
        
        /// <remarks/>
        BDT,
        
        /// <remarks/>
        BGN,
        
        /// <remarks/>
        BHD,
        
        /// <remarks/>
        BIF,
        
        /// <remarks/>
        BMD,
        
        /// <remarks/>
        BND,
        
        /// <remarks/>
        BOB,
        
        /// <remarks/>
        BOV,
        
        /// <remarks/>
        BRL,
        
        /// <remarks/>
        BSD,
        
        /// <remarks/>
        BTN,
        
        /// <remarks/>
        BWP,
        
        /// <remarks/>
        BYR,
        
        /// <remarks/>
        BZD,
        
        /// <remarks/>
        CAD,
        
        /// <remarks/>
        CDF,
        
        /// <remarks/>
        CHF,
        
        /// <remarks/>
        CLF,
        
        /// <remarks/>
        CLP,
        
        /// <remarks/>
        CNY,
        
        /// <remarks/>
        COP,
        
        /// <remarks/>
        COU,
        
        /// <remarks/>
        CRC,
        
        /// <remarks/>
        CUC,
        
        /// <remarks/>
        CUP,
        
        /// <remarks/>
        CVE,
        
        /// <remarks/>
        CZK,
        
        /// <remarks/>
        DJF,
        
        /// <remarks/>
        DKK,
        
        /// <remarks/>
        DOP,
        
        /// <remarks/>
        DZD,
        
        /// <remarks/>
        EEK,
        
        /// <remarks/>
        EGP,
        
        /// <remarks/>
        ERN,
        
        /// <remarks/>
        ETB,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        FJD,
        
        /// <remarks/>
        FKP,
        
        /// <remarks/>
        GBP,
        
        /// <remarks/>
        GEL,
        
        /// <remarks/>
        GHS,
        
        /// <remarks/>
        GIP,
        
        /// <remarks/>
        GMD,
        
        /// <remarks/>
        GNF,
        
        /// <remarks/>
        GTQ,
        
        /// <remarks/>
        GWP,
        
        /// <remarks/>
        GYD,
        
        /// <remarks/>
        HKD,
        
        /// <remarks/>
        HNL,
        
        /// <remarks/>
        HRK,
        
        /// <remarks/>
        HTG,
        
        /// <remarks/>
        HUF,
        
        /// <remarks/>
        IDR,
        
        /// <remarks/>
        ILS,
        
        /// <remarks/>
        INR,
        
        /// <remarks/>
        IQD,
        
        /// <remarks/>
        IRR,
        
        /// <remarks/>
        ISK,
        
        /// <remarks/>
        JMD,
        
        /// <remarks/>
        JOD,
        
        /// <remarks/>
        JPY,
        
        /// <remarks/>
        KES,
        
        /// <remarks/>
        KGS,
        
        /// <remarks/>
        KHR,
        
        /// <remarks/>
        KMF,
        
        /// <remarks/>
        KPW,
        
        /// <remarks/>
        KRW,
        
        /// <remarks/>
        KWD,
        
        /// <remarks/>
        KYD,
        
        /// <remarks/>
        KZT,
        
        /// <remarks/>
        LAK,
        
        /// <remarks/>
        LBP,
        
        /// <remarks/>
        LKR,
        
        /// <remarks/>
        LRD,
        
        /// <remarks/>
        LSL,
        
        /// <remarks/>
        LTL,
        
        /// <remarks/>
        LVL,
        
        /// <remarks/>
        LYD,
        
        /// <remarks/>
        MAD,
        
        /// <remarks/>
        MDL,
        
        /// <remarks/>
        MGA,
        
        /// <remarks/>
        MKD,
        
        /// <remarks/>
        MMK,
        
        /// <remarks/>
        MNT,
        
        /// <remarks/>
        MOP,
        
        /// <remarks/>
        MRO,
        
        /// <remarks/>
        MUR,
        
        /// <remarks/>
        MVR,
        
        /// <remarks/>
        MWK,
        
        /// <remarks/>
        MXN,
        
        /// <remarks/>
        MXV,
        
        /// <remarks/>
        MYR,
        
        /// <remarks/>
        MZN,
        
        /// <remarks/>
        NAD,
        
        /// <remarks/>
        NGN,
        
        /// <remarks/>
        NIO,
        
        /// <remarks/>
        NOK,
        
        /// <remarks/>
        NPR,
        
        /// <remarks/>
        NZD,
        
        /// <remarks/>
        OMR,
        
        /// <remarks/>
        PAB,
        
        /// <remarks/>
        PEN,
        
        /// <remarks/>
        PGK,
        
        /// <remarks/>
        PHP,
        
        /// <remarks/>
        PKR,
        
        /// <remarks/>
        PLN,
        
        /// <remarks/>
        PYG,
        
        /// <remarks/>
        QAR,
        
        /// <remarks/>
        RON,
        
        /// <remarks/>
        RSD,
        
        /// <remarks/>
        RUB,
        
        /// <remarks/>
        RWF,
        
        /// <remarks/>
        SAR,
        
        /// <remarks/>
        SBD,
        
        /// <remarks/>
        SCR,
        
        /// <remarks/>
        SDG,
        
        /// <remarks/>
        SEK,
        
        /// <remarks/>
        SGD,
        
        /// <remarks/>
        SHP,
        
        /// <remarks/>
        SLL,
        
        /// <remarks/>
        SOS,
        
        /// <remarks/>
        SRD,
        
        /// <remarks/>
        STD,
        
        /// <remarks/>
        SVC,
        
        /// <remarks/>
        SYP,
        
        /// <remarks/>
        SZL,
        
        /// <remarks/>
        THB,
        
        /// <remarks/>
        TJS,
        
        /// <remarks/>
        TMT,
        
        /// <remarks/>
        TND,
        
        /// <remarks/>
        TOP,
        
        /// <remarks/>
        TRY,
        
        /// <remarks/>
        TTD,
        
        /// <remarks/>
        TVD,
        
        /// <remarks/>
        TWD,
        
        /// <remarks/>
        TZS,
        
        /// <remarks/>
        UAH,
        
        /// <remarks/>
        UGX,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        UYU,
        
        /// <remarks/>
        UZS,
        
        /// <remarks/>
        VEF,
        
        /// <remarks/>
        VND,
        
        /// <remarks/>
        VUV,
        
        /// <remarks/>
        WST,
        
        /// <remarks/>
        XAF,
        
        /// <remarks/>
        XCD,
        
        /// <remarks/>
        XOF,
        
        /// <remarks/>
        XPD,
        
        /// <remarks/>
        XPF,
        
        /// <remarks/>
        YER,
        
        /// <remarks/>
        ZAR,
        
        /// <remarks/>
        ZMK,
        
        /// <remarks/>
        ZWL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class PaymentMethodDetailType {
        
        private int typeField;
        
        private decimal amountField;
        
        private string paymentMethodInfoField;
        
        /// <remarks/>
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string paymentMethodInfo {
            get {
                return this.paymentMethodInfoField;
            }
            set {
                this.paymentMethodInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class InvoiceRowType {
        
        private int lineNumberField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private int measurementUnitField;
        
        private bool measurementUnitFieldSpecified;
        
        private int invoiceDetailTypeField;
        
        private bool invoiceDetailTypeFieldSpecified;
        
        private decimal netValueField;
        
        private int vatCategoryField;
        
        private decimal vatAmountField;
        
        private int vatExemptionCategoryField;
        
        private bool vatExemptionCategoryFieldSpecified;
        
        private ShipType dienergiaField;
        
        private bool discountOptionField;
        
        private bool discountOptionFieldSpecified;
        
        private decimal withheldAmountField;
        
        private bool withheldAmountFieldSpecified;
        
        private int withheldPercentCategoryField;
        
        private bool withheldPercentCategoryFieldSpecified;
        
        private decimal stampDutyAmountField;
        
        private bool stampDutyAmountFieldSpecified;
        
        private int stampDutyPercentCategoryField;
        
        private bool stampDutyPercentCategoryFieldSpecified;
        
        private decimal feesAmountField;
        
        private bool feesAmountFieldSpecified;
        
        private int feesPercentCategoryField;
        
        private bool feesPercentCategoryFieldSpecified;
        
        private int otherTaxesPercentCategoryField;
        
        private bool otherTaxesPercentCategoryFieldSpecified;
        
        private decimal otherTaxesAmountField;
        
        private bool otherTaxesAmountFieldSpecified;
        
        private decimal deductionsAmountField;
        
        private bool deductionsAmountFieldSpecified;
        
        private string lineCommentsField;
        
        private IncomeClassificationType[] incomeClassificationField;
        
        private ExpensesClassificationType[] expensesClassificationField;
        
        /// <remarks/>
        public int lineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        public decimal quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int measurementUnit {
            get {
                return this.measurementUnitField;
            }
            set {
                this.measurementUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool measurementUnitSpecified {
            get {
                return this.measurementUnitFieldSpecified;
            }
            set {
                this.measurementUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int invoiceDetailType {
            get {
                return this.invoiceDetailTypeField;
            }
            set {
                this.invoiceDetailTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool invoiceDetailTypeSpecified {
            get {
                return this.invoiceDetailTypeFieldSpecified;
            }
            set {
                this.invoiceDetailTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal netValue {
            get {
                return this.netValueField;
            }
            set {
                this.netValueField = value;
            }
        }
        
        /// <remarks/>
        public int vatCategory {
            get {
                return this.vatCategoryField;
            }
            set {
                this.vatCategoryField = value;
            }
        }
        
        /// <remarks/>
        public decimal vatAmount {
            get {
                return this.vatAmountField;
            }
            set {
                this.vatAmountField = value;
            }
        }
        
        /// <remarks/>
        public int vatExemptionCategory {
            get {
                return this.vatExemptionCategoryField;
            }
            set {
                this.vatExemptionCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vatExemptionCategorySpecified {
            get {
                return this.vatExemptionCategoryFieldSpecified;
            }
            set {
                this.vatExemptionCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ShipType dienergia {
            get {
                return this.dienergiaField;
            }
            set {
                this.dienergiaField = value;
            }
        }
        
        /// <remarks/>
        public bool discountOption {
            get {
                return this.discountOptionField;
            }
            set {
                this.discountOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discountOptionSpecified {
            get {
                return this.discountOptionFieldSpecified;
            }
            set {
                this.discountOptionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal withheldAmount {
            get {
                return this.withheldAmountField;
            }
            set {
                this.withheldAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool withheldAmountSpecified {
            get {
                return this.withheldAmountFieldSpecified;
            }
            set {
                this.withheldAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int withheldPercentCategory {
            get {
                return this.withheldPercentCategoryField;
            }
            set {
                this.withheldPercentCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool withheldPercentCategorySpecified {
            get {
                return this.withheldPercentCategoryFieldSpecified;
            }
            set {
                this.withheldPercentCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal stampDutyAmount {
            get {
                return this.stampDutyAmountField;
            }
            set {
                this.stampDutyAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stampDutyAmountSpecified {
            get {
                return this.stampDutyAmountFieldSpecified;
            }
            set {
                this.stampDutyAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int stampDutyPercentCategory {
            get {
                return this.stampDutyPercentCategoryField;
            }
            set {
                this.stampDutyPercentCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stampDutyPercentCategorySpecified {
            get {
                return this.stampDutyPercentCategoryFieldSpecified;
            }
            set {
                this.stampDutyPercentCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal feesAmount {
            get {
                return this.feesAmountField;
            }
            set {
                this.feesAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool feesAmountSpecified {
            get {
                return this.feesAmountFieldSpecified;
            }
            set {
                this.feesAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int feesPercentCategory {
            get {
                return this.feesPercentCategoryField;
            }
            set {
                this.feesPercentCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool feesPercentCategorySpecified {
            get {
                return this.feesPercentCategoryFieldSpecified;
            }
            set {
                this.feesPercentCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int otherTaxesPercentCategory {
            get {
                return this.otherTaxesPercentCategoryField;
            }
            set {
                this.otherTaxesPercentCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool otherTaxesPercentCategorySpecified {
            get {
                return this.otherTaxesPercentCategoryFieldSpecified;
            }
            set {
                this.otherTaxesPercentCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal otherTaxesAmount {
            get {
                return this.otherTaxesAmountField;
            }
            set {
                this.otherTaxesAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool otherTaxesAmountSpecified {
            get {
                return this.otherTaxesAmountFieldSpecified;
            }
            set {
                this.otherTaxesAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal deductionsAmount {
            get {
                return this.deductionsAmountField;
            }
            set {
                this.deductionsAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deductionsAmountSpecified {
            get {
                return this.deductionsAmountFieldSpecified;
            }
            set {
                this.deductionsAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string lineComments {
            get {
                return this.lineCommentsField;
            }
            set {
                this.lineCommentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("incomeClassification")]
        public IncomeClassificationType[] incomeClassification {
            get {
                return this.incomeClassificationField;
            }
            set {
                this.incomeClassificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expensesClassification")]
        public ExpensesClassificationType[] expensesClassification {
            get {
                return this.expensesClassificationField;
            }
            set {
                this.expensesClassificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class ShipType {
        
        private string applicationIdField;
        
        private System.DateTime applicationDateField;
        
        private string doyField;
        
        private string shipIdField;
        
        /// <remarks/>
        public string applicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime applicationDate {
            get {
                return this.applicationDateField;
            }
            set {
                this.applicationDateField = value;
            }
        }
        
        /// <remarks/>
        public string doy {
            get {
                return this.doyField;
            }
            set {
                this.doyField = value;
            }
        }
        
        /// <remarks/>
        public string shipId {
            get {
                return this.shipIdField;
            }
            set {
                this.shipIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class TaxTotalsType {
        
        private sbyte taxTypeField;
        
        private sbyte taxCategoryField;
        
        private bool taxCategoryFieldSpecified;
        
        private decimal underlyingValueField;
        
        private bool underlyingValueFieldSpecified;
        
        private decimal taxAmountField;
        
        private sbyte idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        public sbyte taxType {
            get {
                return this.taxTypeField;
            }
            set {
                this.taxTypeField = value;
            }
        }
        
        /// <remarks/>
        public sbyte taxCategory {
            get {
                return this.taxCategoryField;
            }
            set {
                this.taxCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxCategorySpecified {
            get {
                return this.taxCategoryFieldSpecified;
            }
            set {
                this.taxCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal underlyingValue {
            get {
                return this.underlyingValueField;
            }
            set {
                this.underlyingValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool underlyingValueSpecified {
            get {
                return this.underlyingValueFieldSpecified;
            }
            set {
                this.underlyingValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal taxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        public sbyte id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class InvoiceSummaryType {
        
        private decimal totalNetValueField;
        
        private decimal totalVatAmountField;
        
        private decimal totalWithheldAmountField;
        
        private decimal totalFeesAmountField;
        
        private decimal totalStampDutyAmountField;
        
        private decimal totalOtherTaxesAmountField;
        
        private decimal totalDeductionsAmountField;
        
        private decimal totalGrossValueField;
        
        private IncomeClassificationType[] incomeClassificationField;
        
        private ExpensesClassificationType[] expensesClassificationField;
        
        /// <remarks/>
        public decimal totalNetValue {
            get {
                return this.totalNetValueField;
            }
            set {
                this.totalNetValueField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalVatAmount {
            get {
                return this.totalVatAmountField;
            }
            set {
                this.totalVatAmountField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalWithheldAmount {
            get {
                return this.totalWithheldAmountField;
            }
            set {
                this.totalWithheldAmountField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalFeesAmount {
            get {
                return this.totalFeesAmountField;
            }
            set {
                this.totalFeesAmountField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalStampDutyAmount {
            get {
                return this.totalStampDutyAmountField;
            }
            set {
                this.totalStampDutyAmountField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalOtherTaxesAmount {
            get {
                return this.totalOtherTaxesAmountField;
            }
            set {
                this.totalOtherTaxesAmountField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalDeductionsAmount {
            get {
                return this.totalDeductionsAmountField;
            }
            set {
                this.totalDeductionsAmountField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalGrossValue {
            get {
                return this.totalGrossValueField;
            }
            set {
                this.totalGrossValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("incomeClassification")]
        public IncomeClassificationType[] incomeClassification {
            get {
                return this.incomeClassificationField;
            }
            set {
                this.incomeClassificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expensesClassification")]
        public ExpensesClassificationType[] expensesClassification {
            get {
                return this.expensesClassificationField;
            }
            set {
                this.expensesClassificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0", IsNullable=false)]
    public partial class RequestedDoc {
        
        private continuationTokenType continuationTokenField;
        
        private RequestedDocInvoicesDoc invoicesDocField;
        
        private RequestedDocCancelledInvoicesDoc cancelledInvoicesDocField;
        
        private RequestedDocIncomeClassificationsDoc incomeClassificationsDocField;
        
        private RequestedDocExpensesClassificationDoc expensesClassificationDocField;
        
        /// <remarks/>
        public continuationTokenType continuationToken {
            get {
                return this.continuationTokenField;
            }
            set {
                this.continuationTokenField = value;
            }
        }
        
        /// <remarks/>
        public RequestedDocInvoicesDoc invoicesDoc {
            get {
                return this.invoicesDocField;
            }
            set {
                this.invoicesDocField = value;
            }
        }
        
        /// <remarks/>
        public RequestedDocCancelledInvoicesDoc cancelledInvoicesDoc {
            get {
                return this.cancelledInvoicesDocField;
            }
            set {
                this.cancelledInvoicesDocField = value;
            }
        }
        
        /// <remarks/>
        public RequestedDocIncomeClassificationsDoc incomeClassificationsDoc {
            get {
                return this.incomeClassificationsDocField;
            }
            set {
                this.incomeClassificationsDocField = value;
            }
        }
        
        /// <remarks/>
        public RequestedDocExpensesClassificationDoc expensesClassificationDoc {
            get {
                return this.expensesClassificationDocField;
            }
            set {
                this.expensesClassificationDocField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class continuationTokenType {
        
        private string nextPartitionKeyField;
        
        private string nextRowKeyField;
        
        /// <remarks/>
        public string nextPartitionKey {
            get {
                return this.nextPartitionKeyField;
            }
            set {
                this.nextPartitionKeyField = value;
            }
        }
        
        /// <remarks/>
        public string nextRowKey {
            get {
                return this.nextRowKeyField;
            }
            set {
                this.nextRowKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class RequestedDocInvoicesDoc {
        
        private AadeBookInvoiceType[] invoiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoice")]
        public AadeBookInvoiceType[] invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class RequestedDocCancelledInvoicesDoc {
        
        private CancelledInvoiceType[] cancelledinvoiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cancelledinvoice")]
        public CancelledInvoiceType[] cancelledinvoice {
            get {
                return this.cancelledinvoiceField;
            }
            set {
                this.cancelledinvoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class CancelledInvoiceType {
        
        private long invoiceMarkField;
        
        private long cancellationMarkField;
        
        private System.DateTime cancellationDateField;
        
        /// <remarks/>
        public long invoiceMark {
            get {
                return this.invoiceMarkField;
            }
            set {
                this.invoiceMarkField = value;
            }
        }
        
        /// <remarks/>
        public long cancellationMark {
            get {
                return this.cancellationMarkField;
            }
            set {
                this.cancellationMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime cancellationDate {
            get {
                return this.cancellationDateField;
            }
            set {
                this.cancellationDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class RequestedDocIncomeClassificationsDoc {
        
        private InvoiceIncomeClassificationType[] incomeInvoiceClassificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("incomeInvoiceClassification")]
        public InvoiceIncomeClassificationType[] incomeInvoiceClassification {
            get {
                return this.incomeInvoiceClassificationField;
            }
            set {
                this.incomeInvoiceClassificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class RequestedDocExpensesClassificationDoc {
        
        private InvoiceExpensesClassificationType[] expensesInvoiceClassificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expensesInvoiceClassification")]
        public InvoiceExpensesClassificationType[] expensesInvoiceClassification {
            get {
                return this.expensesInvoiceClassificationField;
            }
            set {
                this.expensesInvoiceClassificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ResponseDoc {
        
        private ResponseType[] responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("response")]
        public ResponseType[] response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResponseType {
        
        private int indexField;
        
        private string statusCodeField;
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        public int index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classificationMark", typeof(long))]
        [System.Xml.Serialization.XmlElementAttribute("errors", typeof(ResponseTypeErrors))]
        [System.Xml.Serialization.XmlElementAttribute("invoiceMark", typeof(long))]
        [System.Xml.Serialization.XmlElementAttribute("invoiceUid", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ResponseTypeErrors {
        
        private ErrorType[] errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error")]
        public ErrorType[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ErrorType {
        
        private string messageField;
        
        private int codeField;
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        classificationMark,
        
        /// <remarks/>
        errors,
        
        /// <remarks/>
        invoiceMark,
        
        /// <remarks/>
        invoiceUid,
    }
}
